
;;; INTRO TO SCALAR VARIABLES IN ASSEMBLY 8086

        ORG 100H                ; START .COM FILE. 
        
;;; THERE ARE THREE TYPES OF BASIC VARIABLES IN ASSSEMBLY 8086:
;;; A) BYTE VARIABLES
;;; B) WORD VARIABLES
;;; C) FLOATING POINT VARIABLES


        
;;; A) SCALAR VARIABLES CONSIST OF A SINGLE BYTE
        
;;; A BYTE ALLOWS TO HOLD UP TO 255 VALUES OF INFO.
;;; SOME OF THE APPLICATIONS OF SCALAR BYTES ARE:
;;;     1) SMALL INTEGERS [0, 255]
;;;     2) SMALL SIGNED INTEGERS [-127, 127]
;;;     3) BOOLEAN VARIABLES
;;;     4) ENUMERATIONS.

;;; THERE ARE THREE DIFFERENT TYPES OF DECLARATIONS:
;;;     I) #variableName db   VALUE
;;;     II) #variableName byte VALUE
;;;     III) #variableName sb   VALUE 

;;; IN ANY ONE OF THE 3 DECLARATIONS, YOU CAN LEFT THE VARIABLE
;;; UNINITIALIZED BY USING A QUESTION MARK (?) ON THE VALUE FIELD

;;; I) AND II) ARE EQUIVALENT FORMS OF DECLARING VARIABLES.
        
        myAge    DB   20        ; MY AGE IN YEARS
        myWeight BYTE 60        ; MY WEIGHT IN KG.

;;; III) USED TO DECLARE SIGNED VARIABLES.

        accountBalance SB -8    ; MY BANK ACCOUNT BALANCE. 
